export interface AlgorithmInfo {
  id: string;
  name: string;
  category: string;
  description: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  timeComplexity: { best: string; average: string; worst: string };
  spaceComplexity: string;
  stable: boolean;
  pseudocode: string[];
  tags: string[];
}

export const algorithms: AlgorithmInfo[] = [
  {
    id: 'bubble-sort',
    name: 'Bubble Sort',
    category: 'Sorting',
    description: 'Repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order.',
    difficulty: 'Easy',
    timeComplexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' },
    spaceComplexity: 'O(1)',
    stable: true,
    pseudocode: [
      'for i = 0 to n-1:',
      '  for j = 0 to n-i-2:',
      '    if arr[j] > arr[j+1]:',
      '      swap(arr[j], arr[j+1])',
      '  mark arr[n-i-1] as sorted',
    ],
    tags: ['comparison', 'in-place'],
  },
  {
    id: 'selection-sort',
    name: 'Selection Sort',
    category: 'Sorting',
    description: 'Finds the minimum element from unsorted part and puts it at the beginning in each iteration.',
    difficulty: 'Easy',
    timeComplexity: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)' },
    spaceComplexity: 'O(1)',
    stable: false,
    pseudocode: [
      'for i = 0 to n-1:',
      '  minIdx = i',
      '  for j = i+1 to n:',
      '    if arr[j] < arr[minIdx]:',
      '      minIdx = j',
      '  swap(arr[i], arr[minIdx])',
    ],
    tags: ['comparison', 'in-place'],
  },
  {
    id: 'insertion-sort',
    name: 'Insertion Sort',
    category: 'Sorting',
    description: 'Builds the final sorted array one item at a time by inserting each element into its correct position.',
    difficulty: 'Easy',
    timeComplexity: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' },
    spaceComplexity: 'O(1)',
    stable: true,
    pseudocode: [
      'for i = 1 to n:',
      '  key = arr[i]',
      '  j = i - 1',
      '  while j >= 0 and arr[j] > key:',
      '    arr[j+1] = arr[j]',
      '    j = j - 1',
      '  arr[j+1] = key',
    ],
    tags: ['comparison', 'in-place', 'adaptive'],
  },
  {
    id: 'merge-sort',
    name: 'Merge Sort',
    category: 'Sorting',
    description: 'Divides the array into halves, sorts each half, then merges them back together.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n log n)' },
    spaceComplexity: 'O(n)',
    stable: true,
    pseudocode: [
      'mergeSort(arr, left, right):',
      '  if left < right:',
      '    mid = (left + right) / 2',
      '    mergeSort(arr, left, mid)',
      '    mergeSort(arr, mid+1, right)',
      '    merge(arr, left, mid, right)',
    ],
    tags: ['divide-and-conquer', 'recursive'],
  },
  {
    id: 'quick-sort',
    name: 'Quick Sort',
    category: 'Sorting',
    description: 'Picks a pivot element and partitions the array around it, recursively sorting each partition.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(n log n)', average: 'O(n log n)', worst: 'O(n²)' },
    spaceComplexity: 'O(log n)',
    stable: false,
    pseudocode: [
      'quickSort(arr, low, high):',
      '  if low < high:',
      '    pi = partition(arr, low, high)',
      '    quickSort(arr, low, pi-1)',
      '    quickSort(arr, pi+1, high)',
      'partition(arr, low, high):',
      '  pivot = arr[high]',
      '  i = low - 1',
      '  for j = low to high-1:',
      '    if arr[j] <= pivot:',
      '      i++; swap(arr[i], arr[j])',
      '  swap(arr[i+1], arr[high])',
    ],
    tags: ['divide-and-conquer', 'in-place'],
  },
  {
    id: 'linear-search',
    name: 'Linear Search',
    category: 'Searching',
    description: 'Sequentially checks each element of the list until a match is found or the whole list has been searched.',
    difficulty: 'Easy',
    timeComplexity: { best: 'O(1)', average: 'O(n)', worst: 'O(n)' },
    spaceComplexity: 'O(1)',
    stable: true,
    pseudocode: [
      'for i = 0 to n-1:',
      '  if arr[i] == target:',
      '    return i',
      'return -1',
    ],
    tags: ['sequential'],
  },
  {
    id: 'binary-search',
    name: 'Binary Search',
    category: 'Searching',
    description: 'Finds a target in a sorted array by repeatedly dividing the search interval in half.',
    difficulty: 'Easy',
    timeComplexity: { best: 'O(1)', average: 'O(log n)', worst: 'O(log n)' },
    spaceComplexity: 'O(1)',
    stable: true,
    pseudocode: [
      'left = 0, right = n - 1',
      'while left <= right:',
      '  mid = (left + right) / 2',
      '  if arr[mid] == target: return mid',
      '  if arr[mid] < target: left = mid + 1',
      '  else: right = mid - 1',
      'return -1',
    ],
    tags: ['divide-and-conquer', 'requires-sorted'],
  },
  {
    id: 'stack',
    name: 'Stack',
    category: 'Data Structures',
    description: 'LIFO (Last In, First Out) data structure. Supports push, pop, and peek operations in O(1).',
    difficulty: 'Easy',
    timeComplexity: { best: 'O(1)', average: 'O(1)', worst: 'O(1)' },
    spaceComplexity: 'O(n)',
    stable: true,
    pseudocode: ['push(val): stack.top++; stack[top] = val', 'pop(): return stack[top--]', 'peek(): return stack[top]'],
    tags: ['linear', 'LIFO'],
  },
  {
    id: 'queue',
    name: 'Queue',
    category: 'Data Structures',
    description: 'FIFO (First In, First Out) data structure. Supports enqueue, dequeue, and peek in O(1).',
    difficulty: 'Easy',
    timeComplexity: { best: 'O(1)', average: 'O(1)', worst: 'O(1)' },
    spaceComplexity: 'O(n)',
    stable: true,
    pseudocode: ['enqueue(val): queue[rear++] = val', 'dequeue(): return queue[front++]', 'peek(): return queue[front]'],
    tags: ['linear', 'FIFO'],
  },
  {
    id: 'linked-list',
    name: 'Linked List',
    category: 'Data Structures',
    description: 'Linear data structure where elements are linked using pointers. Allows O(1) insertion/deletion at known positions.',
    difficulty: 'Easy',
    timeComplexity: { best: 'O(1)', average: 'O(n)', worst: 'O(n)' },
    spaceComplexity: 'O(n)',
    stable: true,
    pseudocode: ['insertFront(val): newNode.next = head; head = newNode', 'delete(val): find node; prev.next = node.next'],
    tags: ['linear', 'dynamic'],
  },
  {
    id: 'bst',
    name: 'Binary Search Tree',
    category: 'Trees',
    description: 'A tree where each node has at most two children, with left < node < right, enabling O(log n) search.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(log n)', average: 'O(log n)', worst: 'O(n)' },
    spaceComplexity: 'O(n)',
    stable: true,
    pseudocode: [
      'insert(val): if val < node: go left',
      '             else: go right',
      'search(val): if val == node: found',
      '             elif val < node: search left',
      '             else: search right',
      'inorder(node): inorder(left); visit(node); inorder(right)',
    ],
    tags: ['tree', 'hierarchical'],
  },
  {
    id: 'bfs',
    name: 'BFS',
    category: 'Graphs',
    description: 'Breadth-First Search explores all neighbors at the current depth before moving to deeper nodes.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(V+E)', average: 'O(V+E)', worst: 'O(V+E)' },
    spaceComplexity: 'O(V)',
    stable: true,
    pseudocode: [
      'BFS(start):',
      '  queue = [start]; visited = {start}',
      '  while queue not empty:',
      '    node = queue.dequeue()',
      '    for each neighbor of node:',
      '      if not visited: visited.add(neighbor); queue.enqueue(neighbor)',
    ],
    tags: ['graph', 'traversal'],
  },
  {
    id: 'dfs',
    name: 'DFS',
    category: 'Graphs',
    description: 'Depth-First Search explores as far as possible along each branch before backtracking.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(V+E)', average: 'O(V+E)', worst: 'O(V+E)' },
    spaceComplexity: 'O(V)',
    stable: true,
    pseudocode: [
      'DFS(node, visited):',
      '  visited.add(node)',
      '  for each neighbor of node:',
      '    if not visited:',
      '      DFS(neighbor, visited)',
    ],
    tags: ['graph', 'traversal', 'recursive'],
  },
  {
    id: 'fibonacci',
    name: 'Fibonacci (DP)',
    category: 'Dynamic Programming',
    description: 'Computes Fibonacci numbers using bottom-up dynamic programming, storing subproblem results in a table.',
    difficulty: 'Easy',
    timeComplexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    spaceComplexity: 'O(n)',
    stable: true,
    pseudocode: [
      'dp[0] = 0; dp[1] = 1',
      'for i = 2 to n:',
      '  dp[i] = dp[i-1] + dp[i-2]',
      'return dp[n]',
    ],
    tags: ['dp', 'memoization'],
  },
  {
    id: 'lcs',
    name: 'Longest Common Subsequence',
    category: 'Dynamic Programming',
    description: 'Finds the longest subsequence common to two strings using a 2D DP table.',
    difficulty: 'Hard',
    timeComplexity: { best: 'O(mn)', average: 'O(mn)', worst: 'O(mn)' },
    spaceComplexity: 'O(mn)',
    stable: true,
    pseudocode: [
      'for i = 1 to m:',
      '  for j = 1 to n:',
      '    if s1[i] == s2[j]:',
      '      dp[i][j] = dp[i-1][j-1] + 1',
      '    else:',
      '      dp[i][j] = max(dp[i-1][j], dp[i][j-1])',
      'backtrack from dp[m][n] to rebuild the subsequence',
    ],
    tags: ['dp', 'strings'],
  },

  {
    id: 'two-sum',
    name: 'Two Sum (Two Pointers)',
    category: 'Patterns',
    description: 'Finds a pair in a sorted array that adds up to a target, using two pointers moving inward from both ends.',
    difficulty: 'Easy',
    timeComplexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    spaceComplexity: 'O(1)',
    stable: true,
    pseudocode: [
      'sort(arr)',
      'lo = 0, hi = n - 1',
      'while lo < hi:',
      '  sum = arr[lo] + arr[hi]',
      '  if sum == target: return [lo, hi]',
      '  if sum < target: lo++',
      '  else: hi--',
    ],
    tags: ['two-pointers', 'array'],
  },
  {
    id: 'container-water',
    name: 'Container With Most Water',
    category: 'Patterns',
    description: 'Finds the pair of bars that traps the most water between them, using two pointers moving inward.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    spaceComplexity: 'O(1)',
    stable: true,
    pseudocode: [
      'lo = 0, hi = n - 1',
      'while lo < hi:',
      '  area = (hi - lo) * min(a[lo], a[hi])',
      '  best = max(best, area)',
      '  if a[lo] < a[hi]: lo++',
      '  else: hi--',
    ],
    tags: ['two-pointers', 'array'],
  },
  {
    id: 'min-subarray-sum',
    name: 'Minimum Size Subarray Sum',
    category: 'Patterns',
    description: 'Finds the shortest contiguous run of numbers whose sum is at least a target, using a growing and shrinking window.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    spaceComplexity: 'O(1)',
    stable: true,
    pseudocode: [
      'left = 0, sum = 0',
      'for right in 0..n-1:',
      '  sum += a[right]',
      '  while sum >= target:',
      '    best = min(best, right - left + 1)',
      '    sum -= a[left]; left++',
    ],
    tags: ['sliding-window', 'array'],
  },
  {
    id: 'kadane',
    name: "Kadane's Algorithm",
    category: 'Patterns',
    description: 'Finds the contiguous subarray with the largest sum by deciding, at each step, whether to extend the current run or start fresh.',
    difficulty: 'Easy',
    timeComplexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    spaceComplexity: 'O(1)',
    stable: true,
    pseudocode: [
      'cur = a[0], best = a[0]',
      'for i in 1..n-1:',
      '  cur = max(a[i], cur + a[i])',
      '  best = max(best, cur)',
    ],
    tags: ['dp', 'array', 'greedy'],
  },
  {
    id: 'sort-colors',
    name: 'Sort Colors',
    category: 'Patterns',
    description: 'Sorts values into three groups in a single pass using low, mid, and high pointers (the Dutch National Flag problem).',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    spaceComplexity: 'O(1)',
    stable: false,
    pseudocode: [
      'low = 0, mid = 0, high = n - 1',
      'while mid <= high:',
      '  if a[mid] is low: swap(low, mid); low++; mid++',
      '  elif a[mid] is high: swap(mid, high); high--',
      '  else: mid++',
    ],
    tags: ['three-way-partition', 'array'],
  },
  {
    id: 'kth-largest',
    name: 'Kth Largest Element',
    category: 'Patterns',
    description: 'Finds the kth largest value without fully sorting, using the same partition step as Quick Sort (Quickselect).',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n²)' },
    spaceComplexity: 'O(log n)',
    stable: false,
    pseudocode: [
      'target = n - k',
      'quickselect(low, high):',
      '  p = partition(low, high)',
      '  if p == target: return a[p]',
      '  elif p < target: quickselect(p+1, high)',
      '  else: quickselect(low, p-1)',
    ],
    tags: ['divide-and-conquer', 'heap-alternative'],
  },
  {
    id: 'product-except-self',
    name: 'Product of Array Except Self',
    category: 'Patterns',
    description: 'Computes, for every index, the product of all other values using a prefix pass and a suffix pass — no division.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    spaceComplexity: 'O(1)',
    stable: true,
    pseudocode: [
      'prefix = 1',
      'for i in 0..n-1: result[i] = prefix; prefix *= a[i]',
      'suffix = 1',
      'for i in n-1..0: result[i] *= suffix; suffix *= a[i]',
    ],
    tags: ['prefix-sum', 'array'],
  },
  {
    id: 'next-greater-element',
    name: 'Next Greater Element',
    category: 'Patterns',
    description: 'Finds, for every value, the next value to its right that is bigger, using a monotonic stack of waiting indices.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    spaceComplexity: 'O(n)',
    stable: true,
    pseudocode: [
      'for i in 0..n-1:',
      '  while stack not empty and a[stack.top] < a[i]:',
      '    result[stack.pop()] = a[i]',
      '  stack.push(i)',
    ],
    tags: ['monotonic-stack', 'array'],
  },
  {
    id: 'ship-capacity',
    name: 'Binary Search on the Answer',
    category: 'Patterns',
    description: 'Finds the minimum shipping capacity that ships all packages within a day limit, by binary searching over possible answers.',
    difficulty: 'Hard',
    timeComplexity: { best: 'O(n log s)', average: 'O(n log s)', worst: 'O(n log s)' },
    spaceComplexity: 'O(1)',
    stable: true,
    pseudocode: [
      'lo = max(weights), hi = sum(weights)',
      'while lo <= hi:',
      '  mid = (lo + hi) / 2',
      '  if daysNeeded(mid) <= days: hi = mid - 1',
      '  else: lo = mid + 1',
    ],
    tags: ['binary-search', 'greedy'],
  },
  {
    id: 'topo-sort',
    name: 'Topological Sort',
    category: 'Graphs',
    description: "Orders tasks so every prerequisite comes first, using Kahn's algorithm: repeatedly take nodes with no remaining prerequisites.",
    difficulty: 'Medium',
    timeComplexity: { best: 'O(V+E)', average: 'O(V+E)', worst: 'O(V+E)' },
    spaceComplexity: 'O(V)',
    stable: true,
    pseudocode: [
      'queue = nodes with in-degree 0',
      'while queue not empty:',
      '  node = queue.dequeue(); order.push(node)',
      '  for each neighbor: indegree[neighbor]--',
      '    if indegree[neighbor] == 0: queue.enqueue(neighbor)',
    ],
    tags: ['graph', 'ordering', 'kahns-algorithm'],
  },
  {
    id: 'union-find',
    name: 'Union-Find (Connected Components)',
    category: 'Graphs',
    description: 'Groups nodes into connected components by merging the sets on either end of every edge.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(E)', average: 'O(E)', worst: 'O(E · V)' },
    spaceComplexity: 'O(V)',
    stable: true,
    pseudocode: [
      'find(x): while parent[x] != x: x = parent[x]; return x',
      'for each edge (u, v):',
      '  if find(u) != find(v): parent[find(u)] = find(v)',
    ],
    tags: ['graph', 'disjoint-set'],
  },
  {
    id: 'cycle-detect-directed',
    name: 'Detect Cycle (Directed Graph)',
    category: 'Graphs',
    description: 'Detects whether a directed graph has a cycle using DFS and a recursion-stack of nodes currently being explored.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(V+E)', average: 'O(V+E)', worst: 'O(V+E)' },
    spaceComplexity: 'O(V)',
    stable: true,
    pseudocode: [
      'dfs(u):',
      '  state[u] = IN_PROGRESS',
      '  for each neighbor v of u:',
      '    if state[v] == IN_PROGRESS: return true  // cycle',
      '    if state[v] == UNVISITED and dfs(v): return true',
      '  state[u] = DONE; return false',
    ],
    tags: ['graph', 'dfs', 'cycle-detection'],
  },
  {
    id: 'knapsack',
    name: '0/1 Knapsack',
    category: 'Dynamic Programming',
    description: 'Picks items with weights and values to maximize total value without exceeding a weight capacity, each item used at most once.',
    difficulty: 'Hard',
    timeComplexity: { best: 'O(n·W)', average: 'O(n·W)', worst: 'O(n·W)' },
    spaceComplexity: 'O(n·W)',
    stable: true,
    pseudocode: [
      'for i in 1..n:',
      '  for c in 0..capacity:',
      '    if weight[i] > c: dp[i][c] = dp[i-1][c]',
      '    else: dp[i][c] = max(dp[i-1][c], dp[i-1][c-weight[i]] + value[i])',
    ],
    tags: ['dp', 'knapsack'],
  },
  {
    id: 'house-robber',
    name: 'House Robber',
    category: 'Dynamic Programming',
    description: 'Finds the most money that can be robbed from a row of houses without ever robbing two houses in a row.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(n)', average: 'O(n)', worst: 'O(n)' },
    spaceComplexity: 'O(n)',
    stable: true,
    pseudocode: [
      'dp[0] = a[0]',
      'dp[1] = max(a[0], a[1])',
      'for i in 2..n-1:',
      '  dp[i] = max(dp[i-1], dp[i-2] + a[i])',
      'answer = dp[n-1]',
    ],
    tags: ['dp', '1d'],
  },
  {
    id: 'lis',
    name: 'Longest Increasing Subsequence',
    category: 'Dynamic Programming',
    description: 'Finds the length of the longest strictly increasing run of values that can be picked from the array, in order.',
    difficulty: 'Medium',
    timeComplexity: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)' },
    spaceComplexity: 'O(n)',
    stable: true,
    pseudocode: [
      'dp[i] = 1 for all i',
      'for i in 1..n-1:',
      '  for j in 0..i-1:',
      '    if a[j] < a[i]: dp[i] = max(dp[i], dp[j] + 1)',
      'answer = max(dp)',
    ],
    tags: ['dp', 'subsequence'],
  },
];

export const categories = ['All', 'Sorting', 'Searching', 'Data Structures', 'Trees', 'Graphs', 'Dynamic Programming', 'Patterns'];